---
apiVersion: v1
kind: Service
metadata:
  name: wechat-h5-backend
  namespace: three-class-backend
spec:
  selector:
   app: wechat-h5-backend
  ports:
   - port: 3000
     targetPort: 3000
     protocol: TCP