---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wechat-h5-backend
  namespace: three-class-backend
spec:
  selector:
    matchLabels:
      app: wechat-h5-backend
  template:
    metadata:
      labels:
        app: wechat-h5-backend
    spec:
      containers:
        - name: wechat-h5-backend
          image: uhub.service.ucloud.cn/iclass/donviewclass-wechat-h5-backend:210225_TS_94a04f6
          resources:
            limits:
              memory: 128Mi
              cpu: "50m"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: iclasssecret
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ1aHViLnNlcnZpY2UudWNsb3VkLmNuIjp7InVzZXJuYW1lIjoiMjI4MzUxMjA3MkBxcS5jb20iLCJwYXNzd29yZCI6ImljbGFzc2RvY2tlciIsImF1dGgiOiJNakk0TXpVeE1qQTNNa0J4Y1M1amIyMDZhV05zWVhOelpHOWphMlZ5In19fQ==
    #{"auths":{"uhub.service.ucloud.cn":{"username":"2283512072@qq.com","password":"iclassdocker","auth":"MjI4MzUxMjA3MkBxcS5jb206aWNsYXNzZG9ja2Vy"}}}
kind: Secret
metadata:
  name: iclasssecret
  namespace: three-class-backend
type: kubernetes.io/dockerconfigjson